#! /bin/sh

set -e

if [ "$1" = "configure" ]; then
	if [ "$DPKG_MAINTSCRIPT_ARCH" = amd64 ]; then
		LIB_ECI_DIR=/usr/lib/x86_64-linux-gnu
		LIB_VOXIN_DIR=/usr/lib/x86_64-linux-gnu
	else
		LIB_ECI_DIR=/usr/lib/i386-linux-gnu
		LIB_VOXIN_DIR=/usr/lib/i386-linux-gnu
	fi
	update-alternatives --install $LIB_ECI_DIR/libibmeci.so libibmeci.so $LIB_VOXIN_DIR/libvoxin.so.1 1
fi

#DEBHELPER#

exit 0


