The voxin installer installs voxin and its dependencies on various GNU/Linux distributions (e.g. Arch Linux, CentOS, Debian, Fedora, Gentoo, openSUSE, Slackware, Slint, Ubuntu,...). 

The current goal is to provide:
- distribution-independent tarballs (installed under /opt), 
- a minimal package providing symlinks to /opt for various package managers, 
- no dependencies on foreign architectures (the x86_64 binaries won't require multi-arch support from the distribution for x86 binaries).

This git repository has been initially copied from libvoxin-debian and replaces it.

The standard 32 bits libraries are built by [[https://buildroot.org][Buildroot]] .

* Build
By default, libvoxin is built, and installed into the local opt/oralux/voxin directory.
A minimal 32 bits rootfilesystem is supposed to be already available (see paragraph "minimal 32 bits rootfilesystem"). 
The build.sh script expects a Debian 8 based distro (mostly due to the libstdc++ dependency of puncfilter). 
See rsync.sh to export voxin-installer to an x86_64 Debian 8 VM (and get.sh to retrieve the built tarballs thereafter).

** Command
#+BEGIN_SRC shell
# build all
cd voxin-installer
./build.sh
#+END_SRC

#+BEGIN_SRC shell
# build all, extract and merge the tarballs in list.vv
./build.sh -t src/list.vv

# This list provides the paths to the necessary tarballs.
# The common tarballs (*all*, *voxind*) are expected to be placed 
# at the beginning of the list

# For example to test English and French, these paths would be:

$HOME/VOXIN/voxin-viavoice/build/packages/voxin-viavoice-all_6.7-1.0-1.txz
$HOME/VOXIN/voxin-viavoice/build/packages/voxin-viavoice-enu_6.7-1.0-1.txz
$HOME/VOXIN/voxin-viavoice/build/packages/voxin-viavoice-fra_6.7-1.0-1.txz

or
$HOME/VOXIN/voxin-nve/build/packages/voxind-nve_1.4.0.x86_64.txz
$HOME/VOXIN/voxin-nve/build/packages/voxin-nve-all_3.3.0-1.txz
$HOME/VOXIN/voxin-nve/build/packages/voxin-nve-enu-nathan-embedded-high_1.0.0-1.txz
$HOME/VOXIN/voxin-nve/build/packages/voxin-nve-frf-thomas-embedded-high_1.0.2-1.txz

#+END_SRC

	
Sequence followed:
- extract files from the minimal 32 bits rfs
- download libstdc++2.10-glibc2.2 from archive.debian.org
- build [[https://github.com/Oralux/libvoxin][libvoxin]] 

** Minimal 32 bits rootfilesystem
The buildroot tarball is expected to be found in build/packages/buildroot_2017.02.9.txz .
This tarball can be (re)built if needed; it is a relatively intensive process (more than one hour, 3.5 GB of storage space).

*** Command
#+BEGIN_SRC shell
cd voxin-installer
./build.sh -b
#+END_SRC
	
*** Standard 32 bits libraries

The rootfilesystem is built by [[https://buildroot.org][Buildroot]] (see its config in src/buildroot/).
The tree is basically :

#+BEGIN_SRC shell
tree rfs32

rfs32
├── lib
│   ├── ld-2.23.so
│   ├── ld-linux.so.2 -> ld-2.23.so
│   ├── libc-2.23.so
│   ├── libc.so.6 -> libc-2.23.so
│   ├── libdl-2.23.so
│   ├── libdl.so.2 -> libdl-2.23.so
│   ├── libm-2.23.so
│   ├── libm.so.6 -> libm-2.23.so
│   ├── libpthread-2.23.so
│   └── libpthread.so.0 -> libpthread-2.23.so
├── lib32 -> lib
└── usr
    ├── bin
    ├── lib
    └── lib32 -> lib


#+END_SRC


* Memo: version 
The program version is stored in src/conf.inc (VOXIN_VER)
