The voxin installer installs voxin and its dependencies on various GNU/Linux distributions (e.g. Arch Linux, Debian, Fedora, Slackware, Ubuntu,...). 

This git repository has been copied from libvoxin-debian and replaces it.

The current goal is to provide :
- distribution-independent tarballs (in /opt directory), 
- a few minimal and stable debian packages, easily converted to other package format, for the other directpries (/usr, ...) 
- no dependencies on foreign architectures (the x86_64 binaries won't require multi-arch support from the distribution for x86 binaries).

* Requirement
Firstly, install the voxin-viavoice archive supplied by Oralux.

* Build
** default
By default, only libvoxin and voxind are built. 
voxin-rfs32 and voxin-libstdc++ are supposed to be already installed (supplied in voxin > 1.15).

*** sources [[https://github.com/Oralux/libvoxin][libvoxin]] 
*** compil
#+BEGIN_SRC shell
cd voxin-installer
./build.sh
#+END_SRC
	
** (optionally) build voxin-libstdc++
*** sources from [[http://archive.debian.org/debian/pool/main/g/gcc-2.95/${ORIG_NAME}_2.95.4-27_i386.deb][Debian Archive]]

voxin-libstdc++ installs the libstdc++ library in the /opt/voxin/rfs32 directory.

*** compil
To build the voxin-libstdc++ package:

#+BEGIN_SRC shell
cd libvoxin-debian
./build.sh -l
#+END_SRC

** (optionally) build voxin-rfs32
*** sources from [[https://buildroot.org][Buildroot]]
The standard 32 bits libraries are built by [[https://buildroot.org][Buildroot]] (see its configuration in src/buildroot/).
The minimal tree is:

#+BEGIN_SRC shell
tree rfs32

rfs32
├── lib
│   ├── ld-2.23.so
│   ├── ld-linux.so.2 -> ld-2.23.so
│   ├── libc-2.23.so
│   ├── libc.so.6 -> libc-2.23.so
│   ├── libdl-2.23.so
│   ├── libdl.so.2 -> libdl-2.23.so
│   ├── libm-2.23.so
│   ├── libm.so.6 -> libm-2.23.so
│   ├── libpthread-2.23.so
│   └── libpthread.so.0 -> libpthread-2.23.so
├── lib32 -> lib
└── usr
    ├── bin
    ├── lib
    └── lib32 -> lib


#+END_SRC

*** compil

#+BEGIN_SRC shell
cd libvoxin-debian
./build.sh -r
#+END_SRC

* Copy the packages to the voxin installer
rm $VOXIN_INSTALLER/packages/all/{voxind*,libvoxin*}
cp build.sig/*deb $VOXIN_INSTALLER/packages/all

