#+TITLE:     Voxin %VERSION% README
#+AUTHOR:

For support or feedback, please send a mail to contact@oralux.org with possibly the log file (log/voxin.log).

* Check the voxin archive

Before any install, you may want to check that your voxin archive (the .tgz file) has a correct checksum.

The checksum file can be downloaded from GitHub under the Oralux account:
#+BEGIN_EXPORT ascii
https://raw.githubusercontent.com/Oralux/voxin-installer/master/check/%VERSION%/SHA512SUM_%VERSION%
#+END_EXPORT

In the following example, our voxin archive (voxin-update-%VERSION%.tgz) is checked against the checksum file (SHA512SUM_%VERSION%). These two files have been copied in the same directory.

In a console, change/cd to this directory; then type:
#+BEGIN_EXPORT ascii
sha512sum --ignore-missing --check SHA512SUM_%VERSION%
#+END_EXPORT

The previous command must return "OK":
#+BEGIN_EXPORT ascii
voxin-update-%VERSION%.tgz: OK
#+END_EXPORT

* General Install

Voxin can be installed system-wide as superuser or locally as regular user.

** System-wide install
Just run voxin-installer.sh as root and answer to the questions.
The packages corresponding to the distribution will be installed.


For example, with voxin-enu-%VERSION% :

#+BEGIN_EXPORT ascii
cd voxin-%VERSION%
cd voxin-enu-%VERSION%
sudo --login $PWD/voxin-installer.sh
#+END_EXPORT

Or without sudo:
#+BEGIN_EXPORT ascii
su --login -c $PWD/voxin-installer.sh
#+END_EXPORT

** Local install
By default, voxin will be installed in your $HOME/.local

./voxin-installer.sh

The -d option supplies a dedicated installation directory:
./voxin-installer.sh -d path_to_directory

Note that speech-dispatcher (>= 0.11) automatically calls the local sd_voxin module (in ~/.local/libexec/speech-dispatcher-modules/).

** Voxin updates
Your download link is usually permanent and points on the last voxin release.

To update Voxin, use one of your download links to get the last version.
If you have Cerence TTS Embedded and IBM TTS voices, just use one of your Cerence TTS Embedded link to update Voxin.

The releases are announced in the [[http://voxin.oralux.net/rss.xml][Voxin RSS feed]].

Voxin is released:
- to complete the list of compatible distros (usually after user request),
- to add new features and fixes (libvoxin offers paths of improvement).

Besides the voxin release, a lighter tarball, the voxin update is available and does not include the text-to-speech package.

** Speech Dispatcher

The Speech Dispatcher voxin output module, sd_voxin, is either already provided by your distribution or otherwise will be installed from the voxin tarball.

The voxin-installer will install its own voxin-speechd-conf and/or voxin-speechd packages if the voxin module is not already installed in your system.

After your authorization, the installer may check each speechd.conf file on your system and add the voxin module if needed.
You will have to select voxin via your screen reader (e.g. see the Orca or Fenrir paragraphs below) because the installer does not modified the default output module in speechd.conf.

speechd.conf can also be modified using spd-conf or simply edited. 
These two possibilities are described below.

*** spd-conf

spd-conf can be launched as normal user (not root user) in a terminal.

Here is an example in Ubuntu 18.04.

spd-conf asks several questions, type voxin as default output module.
spd-conf will accept it even if voxin is not yet in its list of known modules.

Note: ENTER is written below when the ENTER key has been pressed.

#+BEGIN_EXPORT ascii
$ spd-conf

Speech Dispatcher configuration tool

Do you want to setup a completely new configuration? [yes] :
> ENTER

Do you want to create/setup a 'user' or 'system' configuration [user] :
> ENTER

User configuration already exists.

Do you want to rewrite it with a new one? [no] :
>yes
User configuration created in /home/user/.config/speech-dispatcher
Configuring user settings for Speech Dispatcher

Default output module [espeak] :
>voxin
The value you have chosen is not among the suggested values.
You have chosen 'voxin'.
The suggested values are ['espeak', 'flite', 'festival', 'cicero', 'ibmtts']
Do you want to correct your answer? [yes] :
>no

Default language (two-letter iso language code like "en" or "cs") [en] :
> ENTER

Default audio output method [pulse] :
> ENTER

Default speech rate (on the scale of -100..100, 0 is default, 50 is faster, -50 is slower) [0] :
> ENTER

Default speech pitch (on the scale of -100..100, 0 is default, 50 is higher, -50 is lower) [0] :
> ENTER

Do you want to have Speech Dispatcher automatically started from ~/.config/autostart ?
This is usually not necessary, most applications will start Speech Dispatcher automatically. [no] :
> ENTER

Do you want to start/restart Speech Dispatcher now and run some tests? [yes] :
> ENTER
Starting Speech Dispatcher in user-mode
[Sat Dec 26 10:20:47 2020 : 338076] speechd: Speech Dispatcher 0.8.8 starting
Testing Speech Dispatcher using spd_say

Did you hear the message about Speech Dispatcher working? [yes] :
> ENTER
Speech Dispatcher is installed and working!
Speech Dispatcher works. Do you want to skip other tests? [yes] :
> ENTER


Diagnostics results:
Speech Dispatcher is working
End of diagnostics results
#+END_EXPORT
 
*** Editing speechd.conf

The Speech Dispatcher configuration file can be edited manually:
- either comment each 'AddModule' line, then speech-dispatcher should load each present module,
- or add this line to select explicitly the voxin module:
AddModule "voxin" "sd_voxin" "voxin.conf"

Optionally, to set voxin as default module, modify the unique DefaultModule line:
DefaultModule voxin


Finally restart speech-dispatcher (e.g. logout or reboot).

- global conf: /etc/speech-dispatcher/speechd.conf
- local conf (created by spd-conf): $HOME/.config/speech-dispatcher/speechd.conf

** Orca

For Orca/Speech Dispatcher users: the newly installed TTS will be taken in account at the next start of Orca/Speech-dispatcher (if you authorized voxin-installer to update your configuration).
So, you may want to logout or reboot your system.
Then, if needed, configure Orca as indicated below.

In the Orca Screen Reader Preferences window, Voice tab:
- set "Speech system" to "Speech Dispatcher"
- set "Speech synthesizer" to voxin

then press the Apply button.

The Orca preferences window is displayed using this command line:

orca -s

or typing the Orca modifier key + SPACE key

** Emacspeak

The [[https://github.com/Oralux/emacspeak_voxin_install/tags][emacspeak installer]] helps to install Emacspeak with eSpeak and Voxin.

If the sound is choppy under Alsa, please copy the asoundrc file from emacspeak to your home directory as ~/.asoundrc
For example:
cp emacspeak-45.0/share/emacs/site-lisp/emacspeak/servers/linux-outloud/asoundrc $HOME/.asoundrc

** Fenrir

Select the speech-dispatcher driver and the voxin module in settings.conf.
For example in /etc/fenrirscreenreader/settings/settings.conf

driver=speechdDriver
module=voxin

** Speakup connector
You may want to install speechd-up (interface between Speakup and Speech Dispatcher).

** How to uninstall Voxin?
*** System-wide as superuser

Voxin %VERSION% can be uninstalled with this command line:

#+BEGIN_EXPORT ascii
sudo --login $PWD/voxin-installer.sh -u
#+END_EXPORT

Or without sudo:
#+BEGIN_EXPORT ascii
su --login -c "$PWD/voxin-installer.sh -u"
#+END_EXPORT

Please note that the text-to-speech files will be removed too (under /opt/IBM/ibmtts or /opt/oralux/nve).

*** Locally as regular user

./voxin-installer.sh -u

* Compatible GNU/Linux Distributions
** Voxin %VERSION%

The last checked distributions are listed below.
Much more should be compatible (particularly with a local install).
Note that the Cerence TTS Embedded are compatible with x86_64 and ARM architectures whereas IBM TTS is only compatible with x86_64.

For support or feedback, please send a mail to contact@oralux.org with possibly the log file (log/voxin.log).

|---------------------------+-----------------|
| Distributions             | Architectures   |
|---------------------------+-----------------|
| Arch Linux (October 2023) | x86_64          |
| Debian 13 (testing)       | x86_64          |
| Fedora 39 (beta)          | x86_64          |
| Raspberry Pi OS           | armv7l, aarch64 |
| Slint64-15.0              | x86_64          |
| Ubuntu 23.10              | x86_64          |
|---------------------------+-----------------|

* voxin.ini configuration file
The user may now define the default value of several parameters.
- capitalization
- punctuation
- voiceName

and only for IBM TTS:
- dictionaryDir
- useAbbreviation

These values will be overwritten by the calling software
(e.g. speech-dispatcher, emacspeak,...).  The voxin.ini file is
consequently interesting when a parameter is not yet managed by the
calling software.

voxin.ini is expected to be present locally at:
$HOME/.config/voxin/voxin.ini
or if not found, available under the installation directory at:
var/opt/oralux/voxin/voxin.ini

The installer creates a writable default file in
var/opt/oralux/voxin/voxin.ini if none exists.

Brief Example:

[general]
capitalization=icon
#punctuation=none

[viavoice]
dictionaryDir=/var/opt/IBM/ibmtts/dict
useAbbreviation=no

* Dictionaries
User dictionaries are currently only available for IBM TTS.
They are enabled by default by speech-dispatcher: in voxin.conf (or ibmtts.conf), the IbmttsDictionaryFolder variable is set to /var/opt/IBM/ibmtts/dict in case of global installation.

Examples of dictionaries are included in this archive under:
dictionary/var/opt/IBM/ibmtts/dict

* voxin-say command

voxin-say is a command which converts text to speech.

#+BEGIN_EXPORT ascii
EXAMPLES :

# Say 'hello world' and redirect output to an external audio player:
voxin-say "hello world" | aplay

# Read file.txt and save speech to an audio file:
voxin-say -f file.txt -w file.wav
voxin-say -f file.txt > file.wav

# The following command is incorrect because no output is supplied:
voxin-say "Hello all"

# Correct command to read a file in French at 500 words per minute, use 4 jobs to speed up conversion
voxin-say -f file.txt -l fr -s 500 -j 4 -w audio.wav

#+END_EXPORT

