#+TITLE:     Voxin %VERSION% README
#+AUTHOR:

For support or feedback, please send a mail to contact@oralux.org with possibly the log file (log/voxin.log). 

* Check the voxin archive

Before any install, check that your voxin archive (the .tgz file) has a correct checksum.

The checksum file can be downloaded from [[https://raw.githubusercontent.com/Oralux/voxin-installer/master/check/%VERSION%/voxin-%VERSION%.sha512][GitHub under the Oralux account]] .

In the following example, our voxin archive (voxin-update-%VERSION%.tgz) is checked against the checksum file (voxin-%VERSION%.sha512).

These two files have been copied in the same directory.
In a console, change/cd to this directory; then type:

#+BEGIN_ASCII 
sha512sum --ignore-missing --check voxin-%VERSION%.sha512 
#+END_ASCII 

This command must return "OK"
#+BEGIN_ASCII 
voxin-update-%VERSION%.tgz: OK
#+END_ASCII 

* General Install

Just run ./voxin-installer.sh as root and answer to the questions.
For example, on Ubuntu with voxin-enu-%VERSION%:

#+BEGIN_ASCII 
cd voxin-%VERSION%
cd voxin-enu-%VERSION%
sudo --login ./voxin-installer.sh
#+END_ASCII 

On other distributions, use "su --login" instead of "sudo --login"  .

** Voxin updates
Your download url is usually permanent and points on the last voxin release.

The releases are announced in the [[http://voxin.oralux.net/rss.xml][Voxin RSS feed]].

Please note that a release does not yet automatically backup your previous Voxin installation.

Voxin is released several times a year: 
- to complete the list of compatible distros (usually after user request),
- to add new features and fixes (libvoxin offers paths of improvement). 

The [[http://voxin.oralux.net/update/][voxin updates]] includes free softwares and does not include the text-to-speech packages.

** Orca

For Orca/Speech Dispatcher users: the newly installed TTS will be taken in account at the next start of Orca/Speech-dispatcher (if you authorized voxin-installer to update your configuration).
So, you may want to reboot your system.
Then, if needed, configure Orca as indicated below.

In the Orca Preferences window, Speech tab:
- set "Speech system" to "Speech Dispatcher"
- set "Speech synthesizer" to voxin

then press the Apply button.

On some distros, the Orca preferences window is by default hidden and can be displayed using this command line:

orca -s

** Speech Dispatcher

The voxin-installer installs the voxin module for speech-dispatcher, and will update your configuration after your authorization. Otherwise, modify the speechd.conf file of speech-dispatcher (using for example spd-conf, choose the voxin module, not the old ibmtts module ).
Please note that the Speech Dispatcher server will take in account the new configuration after its restart, for example at next reboot.

** Emacspeak

The [[https://github.com/Oralux/emacspeak_voxin_install/releases][emacspeak installer]] helps to install Emacspeak with eSpeak and Voxin.

If the sound is choppy under Alsa, please copy the asoundrc file from emacspeak to your home directory as ~/.asoundrc
For example:
cp emacspeak-45.0/share/emacs/site-lisp/emacspeak/servers/linux-outloud/asoundrc $HOME/.asoundrc

** Speakup connector
You may want to install speechd-up (interface between Speakup and Speech Dispatcher).

We proposed voxinup, the Speakup connector for Voxin; but incompatibilities with the graphical desktop appeared for example in Vinux 5.1.
The [[https://github.com/Oralux/voxinup_install/releases][voxinup_install]] helped to install "voxinup" in Arch Linux or Debian based distros.
The original Speakup connector, "spk-connect-ttsynth", was renamed to "voxinup" to ease at least the typing.

** How to uninstall Voxin?
Voxin %VERSION% can be uninstalled with this command line as root:

./voxin-installer.sh -u

Please note that the text-to-speech files will be removed too (under /opt/IBM/ibmtts or /opt/oralux/nve).

* Compatible GNU/Linux Distributions
** Voxin %VERSION%
From version 2.0, voxin is compatible with much more distributions (and their family: derivatives, parent distro).
The included speech dispatcher modules work with speech-dispatcher version >= 0.8 .

The tested distributions are displayed below. Much more should be compatible.
For support or feedback, please send a mail to contact@oralux.org with possibly the log file (log/voxin.log).

|----------------------------+---------------|
| Tested distributions       | Architectures |
|----------------------------+---------------|
| Arch Linux                 | x86_64        |
| CentOS 7                   | x86_64        |
| Debian 8, 9, 10            | x86_64, i686  |
| Fedora 29, 30              | x86_64        |
| Gentoo                     | x86_64        |
| openSUSE Leap 15.0         | x86_64        |
| openSUSE Tumbleweed-i586   | i686          |
| Slint64-14.2.1.1, 14.2.1.2 | x86_64        |
| Ubuntu 18.04, 19.04        | x86_64        |
|----------------------------+---------------|

** voxin 1.15
|-----------------+------------------------|
| Arch Linux      | 2017-01-14             |
| Debian          | 8, 9                   |
| Fedora          | 25, 26                 |
| Kali            | 2016.2, 2017.2, 2017.3 |
| Sonar GNU/Linux | 16.07                  |
| Ubuntu          | from 14.04 to 18.04    |
| Vinux           | 5.1                    |
|-----------------+------------------------|

* Future Updates

Voxin comes with binary packages for Orca and Speech Dispatcher compatible with various GNU/Linux distributions.

However, these binaries will have to be rebuilt to match forthcoming releases of your distro. 

Please note, that the user can rebuilt them.

If you prefer to download [[http://voxin.oralux.net/update/][forthcoming voxin updates]], please visit the update page or subscribe to the [[http://voxin.oralux.net/rss.xml][Voxin RSS feed]].

* voxin-say command

voxin-say is a command which converts text to speech.

#+BEGIN_ASCII 
EXAMPLES :

# Say 'hello world' and redirect output to an external audio player:
voxin-say "hello world" | aplay

# Read file.txt and save speech to an audio file:
voxin-say -f file.txt -w file.wav
voxin-say -f file.txt > file.wav

# The following command is incorrect because no output is supplied:
voxin-say "Hello all"

# Correct command to read a file in French at 500 words per minute, use 4 jobs to speed up conversion
voxin-say -f file.txt -l fr -s 500 -j 4 -w audio.wav

#+END_ASCII

